# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.
name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

permissions:
  contents: write

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "src Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          path: src

      - name: "build Branchini Kontrol Et"
        uses: actions/checkout@v4
        with:
          ref: build
          path: builds

      - name: Derleme ve kopyalama
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3

      - name: Derleme İşlemi
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x ./gradlew
          ./gradlew make makePluginsJson

          # build klasörünü temizle (klasör kalıyor, içi boşalıyor)
          rm -rf $GITHUB_WORKSPACE/builds/*

          # yeni derlenen dosyaları kopyala
          cp $GITHUB_WORKSPACE/src/**/build/*.cs3 $GITHUB_WORKSPACE/builds/ || true
          cp $GITHUB_WORKSPACE/src/build/plugins.json $GITHUB_WORKSPACE/builds/ || true

      - name: Değişiklikleri Build Branch'e Gönder
        env:
          AKDENIZ: ${{ secrets.AKDENIZ }}
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          if git diff-index --quiet HEAD; then
            echo "No changes detected, skipping push."
          else
            git commit -m "$GITHUB_SHA 'nın Derlenmesi"
            git push --force https://x-access-token:${AKDENIZ}@github.com/${{ github.repository }} build
          fi
