name: CloudStream Derleyici

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: src

      - name: Checkout builds
        uses: actions/checkout@v3
        with:
          ref: builds
          path: builds

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Cloudstream classes.jar
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew build
          mkdir -p libs
          cp build/libs/classes.jar libs/classes.jar

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Commit & Push Builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "$GITHUB_SHA build" || exit 0
          git push --force
