name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

permissions:
  contents: write

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v4
        with:
          ref: "build"
          path: "builds"

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3

      - name: Derleme İşlemi
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x ./gradlew
          ./gradlew make makePluginsJson

          # 'builds' klasörünün içini .git dışında tamamen temizle
          find $GITHUB_WORKSPACE/builds -mindepth 1 ! -name '.git' -exec rm -rf {} + 2>/dev/null || true

          # yeni derlenen dosyaları kopyala
          find $GITHUB_WORKSPACE/src -name "*.cs3" -exec cp {} $GITHUB_WORKSPACE/builds/ \;
          cp $GITHUB_WORKSPACE/src/build/plugins.json $GITHUB_WORKSPACE/builds/ 2>/dev/null || true

      - name: Değişiklikleri Build Branch'e Gönder
        env:
          AKDENIZ: ${{ secrets.AKDENIZ }}
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          if git diff-index --quiet HEAD; then
            echo "Değişiklik yok, push atlanıyor."
          else
            git commit -m "$GITHUB_SHA 'nın Derlenmesi"
            git push --force https://x-access-token:${AKDENIZ}@github.com/${{ github.repository }} build
          fi
