# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.
name: Yenileme

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

permissions:
  contents: write # Git push için gerekli

jobs:
  Yenile:
    runs-on: ubuntu-latest
    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4.6.0
        with:
          distribution: adopt
          java-version: 17

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3.2.2

      - name: Build Klasörünü Tamamen Temizle
        run: |
          rm -rf $GITHUB_WORKSPACE/builds
          mkdir -p $GITHUB_WORKSPACE/builds

      - name: Eklentileri Derle ve Kopyala
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Derlemeleri Build Branch’e Gönder (Force Push)
        env:
          AKDENIZ: ${{ secrets.AKDENIZ }} # Repo secrets'ta token olmalı
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          # Git init değilse başlat
          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
          fi

          # build branch varsa checkout et, yoksa oluştur
          git fetch origin build || true
          git checkout -B build origin/build || git checkout -B build

          # Force commit ve push
          git add -f *
          git commit -m "$GITHUB_SHA 'nın Derlenmesi" || echo "No changes to commit"
          git push -f https://x-access-token:${AKDENIZ}@github.com/${{ github.repository }} build
